version: "3.7"

services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: luizalabs
      POSTGRES_USER: luizalabs
    ports:
      - "5432:5432"

  luizalabs-desafio:
    image: jhonatamenezes/luizalabs-desafio
    environment:
      POSTGRES_HOST: postgres
    ports:
      - "8000:8000"
      - "8001:8001"
    links:
      - postgres
    depends_on:
      - postgres