# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  tests-back:
    docker:
      - image: golang:1.12
        environment:
          TEST_DATABASE_URL: postgresql://luizalabs@localhost/luizalabs
      - image: postgres:11-alpine
        environment:
          POSTGRES_PASSWORD: luizalabs
          POSTGRES_USER: luizalabs
        ports:
          - "5432:5432"
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            apt-get update
            apt-get install -y postgresql-client
            psql -d $TEST_DATABASE_URL < back/sql/1.sql
      - run:
          name: golang tests
          command: |
            cd back && go test ./...

  tests-front:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            apt-get update
            apt-get install -y git
            cd front && npm install
      - run:
          name: vuejs tests
          command: |
            cd front && npm run test:unit

workflows:
  version: 2
  build-image:
    jobs:
      - tests-back
      - tests-front